# HSM Backend Configuration
# API Credentials, are overwritten on production.
api.username=admin
api.password=admin

db.host=hsm-backend-db
db.port=5432
db.name=hsm
db.user=hsmuser
db.password=hsmpassword
